sudo: required
dist: trusty
language: c

matrix:
  fast_finish: true
  # list only supported gcc versions: https://gcc.gnu.org/
  include:
    # https://wiki.ubuntu.com/ToolChain#GCC
    # https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: COMPILER=gcc-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env: COMPILER=gcc-7
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env: COMPILER=gcc-8
    # http://releases.llvm.org/
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: COMPILER=clang-4.0
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env: COMPILER=clang-5.0
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env: COMPILER=clang-6.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install autopoint xsltproc docbook-xml docbook-xsl libxml2-utils

script:
  - $COMPILER --version
  - autopoint --version
  - ./autogen.sh
  - ./configure CC=$COMPILER --disable-prelude --enable-regenerate-docu
  - make
  - make check
  - make distcheck

# vim:et:ts=2:sw=2
